export const ADD_AUDIO_TRACK = 'ADD_AUDIO_TRACK';
export const REMOVE_ALL_TRACKS = 'REMOVE_ALL_TRACKS';
export const REMOVE_TRACK = 'REMOVE_TRACK';

export const UPDATE_TRACK_NAME = 'UPDATE_TRACK_NAME';
