export const ADD_AUDIO_TRACK = 'ADD_AUDIO_TRACK';
export const REMOVE_ALL_TRACKS = 'REMOVE_ALL_TRACKS';
export const REMOVE_TRACK = 'REMOVE_TRACK';

export const UPDATE_TRACK_NAME = 'UPDATE_TRACK_NAME';
export const ADD_EFFECT = 'ADD_EFFECT';
export const CHANGE_EFFECT = 'CHANGE_EFFECT';
export const REMOVE_EFFECT = 'REMOVE_EFFECT';